import App from './App.vue'
import { createApp } from 'vue'
import {
  ElRow,
  ElCol,
  ElContainer,
  ElHeader,
  ElFooter,
  ElAside,
  ElMain,
  ElIcon,
  ElButton,
  ElLink,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElCheckbox,
  ElCheckboxButton,
  ElCheckboxGroup,
  ElInput,
  ElInputNumber,
  ElSelect,
  ElOption,
  ElOptionGroup,
  ElCascader,
  ElCascaderPanel,
  ElSwitch,
  ElSlider,
  ElTimePicker,
  ElTimeSelect,
  ElDatePicker,
  ElUpload,
  ElRate,
  ElColorPicker,
  ElTransfer,
  ElForm,
  ElFormItem,
  ElTag,
  ElProgress,
  ElTree,
  ElPagination,
  ElBadge,
  ElAvatar,
  ElAlert,
  ElLoading,
  ElMenu,
  ElMenuItem,
  ElSubmenu,
  ElMenuItemGroup,
  ElTabs,
  ElTabPane,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElPageHeader,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElSteps,
  ElStep,
  ElDialog,
  ElTooltip,
  ElPopover,
  ElPopconfirm,
  ElCard,
  ElCarousel,
  ElCarouselItem,
  ElCollapse,
  ElCollapseItem,
  ElTimeline,
  ElTimelineItem,
  ElDivider,
  ElCalendar,
  ElImage,
  ElBacktop,
  ElInfiniteScroll,
  ElDrawer,
  ElScrollbar
} from 'element3'

createApp(App)
  .use(ElRow)
  .use(ElCol)
  .use(ElContainer)
  .use(ElHeader)
  .use(ElFooter)
  .use(ElAside)
  .use(ElMain)
  .use(ElIcon)
  .use(ElButton)
  .use(ElLink)
  .use(ElRadio)
  .use(ElRadioButton)
  .use(ElRadioGroup)
  .use(ElCheckbox)
  .use(ElCheckboxButton)
  .use(ElCheckboxGroup)
  .use(ElInput)
  .use(ElInputNumber)
  .use(ElSelect)
  .use(ElOption)
  .use(ElOptionGroup)
  .use(ElCascader)
  .use(ElCascaderPanel)
  .use(ElSwitch)
  .use(ElSlider)
  .use(ElTimePicker)
  .use(ElTimeSelect)
  .use(ElDatePicker)
  .use(ElUpload)
  .use(ElRate)
  .use(ElColorPicker)
  .use(ElTransfer)
  .use(ElForm)
  .use(ElFormItem)
  .use(ElTag)
  .use(ElProgress)
  .use(ElTree)
  .use(ElPagination)
  .use(ElBadge)
  .use(ElAvatar)
  .use(ElAlert)
  .use(ElLoading)
  .use(ElMenu)
  .use(ElMenuItem)
  .use(ElSubmenu)
  .use(ElMenuItemGroup)
  .use(ElTabs)
  .use(ElTabPane)
  .use(ElBreadcrumb)
  .use(ElBreadcrumbItem)
  .use(ElPageHeader)
  .use(ElDropdown)
  .use(ElDropdownItem)
  .use(ElDropdownMenu)
  .use(ElSteps)
  .use(ElStep)
  .use(ElDialog)
  .use(ElTooltip)
  .use(ElPopover)
  .use(ElPopconfirm)
  .use(ElCard)
  .use(ElCarousel)
  .use(ElCarouselItem)
  .use(ElCollapse)
  .use(ElCollapseItem)
  .use(ElTimeline)
  .use(ElTimelineItem)
  .use(ElDivider)
  .use(ElCalendar)
  .use(ElImage)
  .use(ElBacktop)
  .use(ElInfiniteScroll)
  .use(ElDrawer)
  .use(ElScrollbar)
